# ===================================================================
# IKEA BILRESA E2490 Scroll Wheel – Matter Edition
# Blueprint Template v1.0.0
#
# Internal Versioning:
#   schema_version: 1.0.0
#   last_updated: 2025-12-18
#
# Power-User Notes:
#   - This device exposes three event entities, one per selected area button.
#   - You must select the correct event entity for Button 1, Button 2 and Button 3.
#   - Each press updates the entity state (timestamp) and sets attributes.event_type.
# ===================================================================

blueprint:
  name: IKEA BILRESA E2490 Scroll Wheel (Matter)
  author: bjornh2
  description: >
    Button-featured automation for the IKEA BILRESA E2490 Matter wheel
    remote. Supports single press, double press, and long press (on release)
    for three buttons. Uses event entities exposed by Home Assistant for
    Matter devices. Single-press actions are prioritized for reliability.
    The wheel functions are not supported in this version.
  domain: automation
  source_url: https://github.com/bjornh2/haos-blueprints
  homeassistant:
    min_version: 2025.12.0

  input:
    target_device:
      name: BILRESA Scroll Wheel Device
      description: >
        Select the IKEA BILRESA E2490 Scroll Wheel device. This is informational only in
        v1.0.0; triggers are bound to the per-button event entities below.
      selector:
        device:
          filter:
            - manufacturer: IKEA of Sweden

    button1_event:
      name: Button 1 – Event Entity
      description: >
        Select the event entity for Button 1 (for example:
        Button(3) BILRESA Scroll Wheel).
      selector:
        entity:
          domain: event

    button2_event:
      name: Button 2 – Event Entity
      description: >
        Select the event entity for Button 2 (for example:
        Button(6) BILRESA Scroll Wheel).
      selector:
        entity:
          domain: event

    button3_event:
      name: Button 3 – Event Entity
      description: >
        Select the event entity for Button 3 (for example:
        Button(9) BILRESA Scroll Wheel).
      selector:
        entity:
          domain: event

    # ---------------------------------------------------------------
    # BUTTON 1 ACTIONS
    # ---------------------------------------------------------------

    button1_single:
      name: Button 1 – Single Press
      description: Action for Button 1 single press (multi_press_1).
      default: []
      selector:
        action: {}

    button1_double:
      name: Button 1 – Double Press
      description: Action for Button 1 double press (multi_press_2).
      default: []
      selector:
        action: {}

    button1_long:
      name: Button 1 – Long Press (on release)
      description: Action for Button 1 long press completion (long_release).
      default: []
      selector:
        action: {}

    # ---------------------------------------------------------------
    # BUTTON 2 ACTIONS
    # ---------------------------------------------------------------

    button2_single:
      name: Button 2 – Single Press
      description: Action for Button 2 single press (multi_press_1).
      default: []
      selector:
        action: {}

    button2_double:
      name: Button 2 – Double Press
      description: Action for Button 2 double press (multi_press_2).
      default: []
      selector:
        action: {}

    button2_long:
      name: Button 2 – Long Press (on release)
      description: Action for Button 2 long press completion (long_release).
      default: []
      selector:
        action: {}

    # ---------------------------------------------------------------
    # BUTTON 3 ACTIONS
    # ---------------------------------------------------------------

    button3_single:
      name: Button 3 – Single Press
      description: Action for Button 3 single press (multi_press_1).
      default: []
      selector:
        action: {}

    button3_double:
      name: Button 3 – Double Press
      description: Action for Button 3 double press (multi_press_2).
      default: []
      selector:
        action: {}

    button3_long:
      name: Button 3 – Long Press (on release)
      description: Action for Button 3 long press completion (long_release).
      default: []
      selector:
        action: {}

# ===================================================================
# AUTOMATION LOGIC
# ===================================================================

variables:
  button1_entity: !input button1_event
  button2_entity: !input button2_event
  button3_entity: !input button3_event

trigger:
  - platform: state
    id: button1
    entity_id: !input button1_event
  - platform: state
    id: button2
    entity_id: !input button2_event
  - platform: state
    id: button3
    entity_id: !input button3_event
  # No 'to:' filter because event entities use timestamp states

condition: []

action:
  - variables:
      press_type: "{{ trigger.to_state.attributes.event_type }}"
      trigger_id: "{{ trigger.id }}"

  - choose:

      # -------------------------------------------------------------
      # BUTTON 1
      # -------------------------------------------------------------

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'multi_press_1' }}
        sequence: !input button1_single

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'multi_press_2' }}
        sequence: !input button1_double

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button1' and press_type == 'long_release' }}
        sequence: !input button1_long

      # -------------------------------------------------------------
      # BUTTON 2
      # -------------------------------------------------------------

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'multi_press_1' }}
        sequence: !input button2_single

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'multi_press_2' }}
        sequence: !input button2_double

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button2' and press_type == 'long_release' }}
        sequence: !input button2_long

      # -------------------------------------------------------------
      # BUTTON 3
      # -------------------------------------------------------------

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button3' and press_type == 'multi_press_1' }}
        sequence: !input button3_single

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button3' and press_type == 'multi_press_2' }}
        sequence: !input button3_double

      - conditions:
          - condition: template
            value_template: >
              {{ trigger_id == 'button3' and press_type == 'long_release' }}
        sequence: !input button3_long

mode: restart